### ISSUE TITLE
only need java runtime 

### ISSUE THREAD

**Issue by Terry-Shi** [apache/incubator-openwhisk-deploy-kube#103]
is that possible to only include java runtime in invoker.yml
like this:
- name: "RUNTIMES_MANIFEST"
   value: '{ "defaultImagePrefix": "openwhisk", "defaultImageTag": "latest", "runtimes": { "java": [ { "kind": "java", "default": true, "image": { "name": "java8action" }, "deprecated": false, "attached": { "attachmentName": "jarfile", "attachmentType": "application/java-archive" }, "sentinelledLogs": false, "requireMain": true } ] }}'

**Comment by rabbah** [comment]
You’ll have to disable the heath protocol which assumes node. And the invoker might also assume node6 is available for stem cells.

**Comment by dgrove-oss** [comment]
I think @rabbah answered the question, so this issue can be closed.  An issue to make node6 optional would belong in the main openwhisk repo.
