### ISSUE TITLE
WHISK_API_HOST_NAME not set correctly in invoker.yml

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-deploy-kube#108]
invoker.yml sets WHISK_API_HOST_NAME to nginx.openwhisk (the internal service name for the nginx engine).  This is wrong; the only use of this envvar is to set __OW_API_HOST in the user function container's environment --  we need any call backs from the user containers to go in through the front door ingress, not short-circuit to an internal route (that will not even be reachable to them from a properly secured deployment).

**Comment by dgrove-oss** [comment]
working on a fix now.

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk-deploy-kube/commit/9f8e75d7ac221c6314ad9bc2d2547baa9306ddf8.
