### ISSUE TITLE
Failed to create api for a java web action

### ISSUE THREAD

**Issue by Terry-Shi** [apache/incubator-openwhisk-deploy-kube#109]
Here are the key steps I used:

$ ./wsk action invoke --result hello --param name Terry --insecure
{
    "greeting": "Hello Terry!"
}

$ ./wsk action update hello --web true --insecure
ok: updated action hello

$ ./wsk api create /api-demo/v1 /hello get hello --insecure --response-type json
error: Unable to create API: The requested resource does not exist. (code 22460)

**Comment by Terry-Shi** [comment]
I guess this is also because of #79 .
anyone can help me bypass this issue ?

**Comment by dgrove-oss** [comment]
Made a little progress on this today with https://github.com/apache/incubator-openwhisk-deploy-kube/pull/123  

Now failing with a different error: 
```
daves-mbp-2:routemgmt dgrove$ wsk api create /api-demo/v1 /hello get hello --response-type json
error: Unable to create API: API creation failure: API swagger generation error: TypeError: Cannot read property '2' of null
```

**Comment by dgrove-oss** [comment]
Hi @Terry-Shi, I made some progress on this yesterday and today.  It is now working for me with the changes in #133 and https://github.com/apache/incubator-openwhisk/pull/3125 (since I'm deploying on a cluster with an Ingress that does URL rewriting).
