### ISSUE TITLE
Change default system throttling limits

### ISSUE THREAD

**Issue by ngibanel** [apache/incubator-openwhisk-deploy-kube#113]
Hello,

From the Openwhisk documentation it is possible to [change default system throttling limits](https://github.com/apache/incubator-openwhisk/blob/master/ansible/README.md#changing-limits)
 (invocationsPerMinute, firesPerMinute, ...) by modifying the `group_vars` 

Is it possible to set limits when we deploy Openwhisk to a Kubernetes cluster ?

Thanks.

**Comment by csantanapr** [comment]
Hi @ngibanel 

Yes you can adjust the limits. 
This is done via environment variables passed to the controller. 
See here to change them https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/kubernetes/controller/controller.yml

**Comment by ngibanel** [comment]
Thanks.
