### ISSUE TITLE
Inferring sane defaults for routemanegement

### ISSUE THREAD

**Issue by kameshsampath** [apache/incubator-openwhisk-deploy-kube#159]
When installing route management job we could have few values for the apimanagement and apigateway be inferred form the cluster env and set to those sane defaults.

**Comment by dgrove-oss** [comment]
@kameshsampath -- I think you were going to look at doing a PR for this based on the slack discussion.  Is that still in the works?  (trying to clear out open issues...).

**Comment by kameshsampath** [comment]
@dgrove-oss  -- yes I will send in a PR for this soon. Please leave it for now will get back to this in few days.

**Comment by dgrove-oss** [comment]
With the switch over to Helm, I think this specific configuration problem has been solved.  Much less for the user to specify explicitly.
