### ISSUE TITLE
x509: certificate signed by unknown authority accessing Nginx in Windows 10

### ISSUE THREAD

**Issue by Dalfons0** [apache/incubator-openwhisk-deploy-kube#161]
Hello,
I'm trying to use Openwhisk locally in Windows 10 using minikube, deploying each service following the guidelines in this repository step by step. But when I have all the services deployed and I try to execute any command with the Openwhisk CLI, I get the following error:

![image pasted at 2018-3-6 15-46](https://user-images.githubusercontent.com/24602242/37083521-0bd26c28-21f0-11e8-9573-db65575c998d.png)

Also, it's worth mentioning that, although I'm using Windows, I have generated the certificate with the _certs.sh_ allocated in the _~/kubernetes/nginx_ folder using cmder (a bash console emulator). So, I wonder if anyone can throw some light on this problem, and clarify which path to follow  to solve it will be greatly appreciated.

Thanks in advance.

**Comment by dgrove-oss** [comment]
hi.  When using the self-signed certificate generated by certs.sh, you need to use `wsk -i` instead of `wsk`.   

> Note: if you installed self-signed certificates when you configured Nginx, you will need to use wsk -i to suppress certificate checking. This works around cannot validate certificate errors from the wsk CLI.

**Comment by Dalfons0** [comment]
Hello, I also had tried that, but I was getting the error:
 
![image](https://user-images.githubusercontent.com/24602242/37163849-1a70ca9a-22f9-11e8-869a-f471f35c2da5.png)

But how you emphasized, I decided to re-check all the auth steps performed in the process, and I encountered that the problem in the CLI whisk auth:

![image](https://user-images.githubusercontent.com/24602242/37164201-eeeb430e-22f9-11e8-9203-9cf7b518397c.png)

The problem was that I was executing the command ```wsk property set --auth `cat ../cluster-setup/auth.guest` --apihost API_HOST``` in a non-bash console, so the auth.gest file wasn't being read :S.

Thanks for your comment anyway.

**Comment by csantanapr** [comment]
>I'm trying to use Openwhisk locally in Windows 10 using minikube,

Woot 🎉 🌮 

@Dalfons0 let us know how successful you are deploying on windows and what things we could improve, always welcome notes or docs updates for windows user to take into account when deploying

You can join the OpenWhisk mailing list or the Slack team http://openwhisk.incubator.apache.org/slack.html

@mdeuser this would interest you since your primary workstation is Windows !! No more Vagrant 
Native Kube Support in OpenWhisk FTW !!!!!!!
