### ISSUE TITLE
issue about couchdb container  (Error syncing pod)

### ISSUE THREAD

**Issue by z14572** [apache/incubator-openwhisk-deploy-kube#168]
when I deploy openwhisk for kube ,   run the script file "build.sh", Failed to finish deploying CouchDB.

 kubectl get pods -n openwhisk
NAME                       READY     STATUS              RESTARTS   AGE
couchdb-3999250316-4f8m1   0/1       ContainerCreating   0          2h

kubectl describe pod couchdb-3999250316-4f8m1 -n openwhisk
Name:		couchdb-3999250316-4f8m1
Namespace:	openwhisk
Node:		greenvm-z14572v1/172.27.10.68
Start Time:	Wed, 21 Mar 2018 10:06:47 +0000
Labels:		name=couchdb
		pod-template-hash=3999250316
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"openwhisk","name":"couchdb-3999250316","uid":"2bea5121-2cde-11e8-bb4a-fa163e62c6a...
Status:		Pending
IP:		
Created By:	ReplicaSet/couchdb-3999250316
Controlled By:	ReplicaSet/couchdb-3999250316
Containers:
  couchdb:
    Container ID:	
    Image:		openwhisk/kube-couchdb
    Image ID:		
    Port:		5984/TCP
    Command:
      /init.sh
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Readiness:		http-get http://:5984/test_activations delay=60s timeout=1s period=10s #success=1 #failure=10
    Environment:
      DB_PREFIX:	<set to the key 'db_prefix' of config map 'db.config'>	Optional: false
      DB_HOST:		127.0.0.1
      COUCHDB_USER:	<set to the key 'db_username' in secret 'db.auth'>	Optional: false
      COUCHDB_PASSWORD:	<set to the key 'db_password' in secret 'db.auth'>	Optional: false
      DB_PORT:		5984
      NODENAME:		couchdb0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pgdbz (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-pgdbz:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-pgdbz
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  2h		0s		162	kubelet, greenvm-z14572v1			Warning		FailedSync	Error syncing pod

I think maybe the couchdb image is not present. then I download the couchdb image by "docker pull  openwhisk/kube-couchdb" , and update the imagePullPolicy from Always to  Never,            also the same result  "Error syncing pod"

**Comment by dgrove-oss** [comment]
`openwhisk/kube-couchdb` is the first container the `build.sh` script attempts to deploy.  I would suggest making sure that your Kube cluster can pull images from dockerhub and create pods with them.  At first glance, this looks to me more like a general problem creating containers with images pulled from dockerhub than a specific problem with the kube-couchdb image.

**Comment by dgrove-oss** [comment]
Closing as idle; please reopen with more details if you are still having problems.
