### ISSUE TITLE
Issues deploying with custom docker images

### ISSUE THREAD

**Issue by mlangbehn** [apache/incubator-openwhisk-deploy-kube#17]
## Summary

Deploying with custom docker images fails on `routemgmt : install route management actions`.

## Steps to reproduce

Modify configuration to use new images:

* ansible-kube/environments/kube/files/nginx.yml
    ```yaml
    34       containers:
    35       - name: nginx
    36         imagePullPolicy: Always
    37         image: [account_name]/whisk_nginx
    38         ports:
    ```
* configure/configure_whisk.yml
    ```yaml
    17       containers:
    18       - name: configure-openwhisk
    19         image: [account_name]/whisk_config:v1.5.6-dev
    20         imagePullPolicy: Always
    ```

## Log snippet

*Verbose logging enabled for ansible*

```text
TASK [routemgmt : install route management actions] ****************************
task path: /incubator-openwhisk-deploy-kube/ansible/roles/routemgmt/tasks/deploy.yml:3
Monday 19 June 2017  21:16:38 +0000 (0:00:08.756)       0:05:33.797 *********** 
fatal: [ansible]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'cli_path' is undefined\n\nThe error appears to have been in '/incubator-openwhisk-deploy-kube/ansible/roles/routemgmt/tasks/deploy.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Install the API Gateway route management actions.\n- name: install route management actions\n  ^ here\n"
}
```

**Comment by mlangbehn** [comment]
The file that is causing the issue is [ansible-kube/roles/routemgmt/tasks/deploy.yml](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/ansible-kube/roles/routemgmt/tasks/deploy.yml#L4), which calls `cli_path` (a variable which doesn't seem to be getting set anywhere). The correlating [file in apache/incubator-openwhisk](https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/routemgmt/tasks/deploy.yml#L4) uses `cli.path` instead.

Changing the variable from `cli_path` to `cli.path` does not resolve the issue, but it does change the failure message. I'm rerunning with the changed variable name and will post logs after the test completes.

**Comment by DanLavine** [comment]
Seems like there are some changes since I built the last images. This is that TODO section in my travis builds... having some way of automating this so it stays up to date, but think the entire build process is working towards making things not need Ansible. I can create new images and fix the new configure issues.

**Comment by DanLavine** [comment]
So I just built everything on a Ubuntu VM from scratch and ran through the deployment just fine. I think there is an issue if you build the images from scratch on a MAC. What i think is happening is that when the CLI is built, the process mounts in a number of files from the Host machine. Golang must then think it is being built for MAC and so it builds the wrong executable type. I will submit something to the docs to address this.

**Comment by mlangbehn** [comment]
Just left a comment on apache/incubator-openwhisk-deploy-kube#19. I also will verify that I am able to deploy as expected via images built on Linux.

**Comment by mlangbehn** [comment]
@DanLavine, I just ran a test where I built my docker images on an Ubuntu 16.04 machine, and reproduced the issue.

Output from `git diff master`:
```diff
diff --git a/ansible-kube/environments/kube/files/nginx.yml b/ansible-kube/environments/kube/files/nginx.yml
index d9780b2..c12e10b 100644
--- a/ansible-kube/environments/kube/files/nginx.yml
+++ b/ansible-kube/environments/kube/files/nginx.yml
@@ -34,7 +34,7 @@ spec:
       containers:
       - name: nginx
         imagePullPolicy: Always
-        image: danlavine/whisk_nginx
+        image: eventingmonkey/whisk_nginx
         ports:
         - name: http
           containerPort: 80
diff --git a/configure/configure_whisk.yml b/configure/configure_whisk.yml
index 4306f95..2f4a1b5 100644
--- a/configure/configure_whisk.yml
+++ b/configure/configure_whisk.yml
@@ -16,6 +16,6 @@ spec:
       restartPolicy: Never
       containers:
       - name: configure-openwhisk
-        image: danlavine/whisk_config:v1.5.6
+        image: eventingmonkey/whisk_config:v1.5.6-dev
         imagePullPolicy: Always
         command: [ "/incubator-openwhisk-deploy-kube/configure/configure.sh" ]
```

Here is the error from the deploy:

```text
TASK [routemgmt : install route management actions] ****************************
Tuesday 20 June 2017  20:59:52 +0000 (0:00:08.592)       0:05:32.825 ********** 
fatal: [ansible]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'cli_path' is undefined\n\nThe error appears to have been in '/incubator-openwhisk-deploy-kube/ansible/roles/routemgmt/tasks/deploy.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Install the API Gateway route management actions.\n- name: install route management actions\n  ^ here\n"}
```

**Comment by bbrowning** [comment]
@mlangbehn This failure is because tof the reason pointed out above - cli_path was renamed to cli.path in OpenWhisk master - and the ansible-kube scripts just need to be updated to reflect that.

Because the `whisk_config` Docker image clones OpenWhisk master when it gets built, it's easy to run into issues like this where rebuilding the Docker image fails (because it pulls in a newer OpenWhisk) compared to just running the existing published image. For reproducible builds, we may want to look into either pinning the git clone to a specific commit or removing the need to clone the main OpenWhisk repo in the Dockerfile.

Otherwise we'll run into issues like this where a build succeeds at some point in time but the exact same build fails at a future date.

**Comment by DanLavine** [comment]
Hmm. idk what happened when I built my image, I updated the OpenWhisk repo and everything, then rebuilt. Looking at the diff though it is still using the last commit I pulled. Will update the property. Think that other issue was resolved though if you change the property to the correct value?

**Comment by DanLavine** [comment]
@bbrowning @mlangbehn I update the Docker images and should have the newest version of OpenWhisk built into it. Made it a part of pr #19

**Comment by mlangbehn** [comment]
Starting yesterday, my testing has been failing with an issue connecting to the controller. I'm working on debugging it now, but here is the log:

```shell
% kubectl -n openwhisk logs -f $(kubectl -n openwhisk get pods | awk '/controller/ { print $1 }')                                            master=
[2017-06-23T14:28:59.951Z] [INFO] Slf4jLogger started 
[2017-06-23T14:29:00.669Z] [INFO] [??] [Config] environment set value for consulserver.host 
[2017-06-23T14:29:00.679Z] [INFO] [??] [Config] environment set value for whisk.version.date 
[2017-06-23T14:29:00.681Z] [INFO] [??] [Config] environment set value for whisk.version.buildno 
[2017-06-23T14:29:00.682Z] [INFO] [??] [Config] environment set value for consul.host.port4 
[2017-06-23T14:29:00.683Z] [INFO] [??] [Config] environment set value for port 
[2017-06-23T14:29:00.686Z] [INFO] [??] [WhiskConfig] reading properties from consul at consul.openwhisk:8500 
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: controller instance required
	at scala.Predef$.require(Predef.scala:224)
	at whisk.core.controller.Controller$.main(Controller.scala:193)
	at whisk.core.controller.Controller.main(Controller.scala)
```

**Comment by DanLavine** [comment]
This is a bigger issue. The HA Controller code was pulled in which breaks the controller. Have a fix. Just need to rebase it over all the current PRs and test it.

**Comment by mlangbehn** [comment]
@DanLavine: Fabulous. I'd be happy to test and/or review change requests.

**Comment by DanLavine** [comment]
@mlangbehn Just pushed the code. Was just a number of config changes that had to go in.  Everything should be green now.

**Comment by mlangbehn** [comment]
@DanLavine: Thanks, this issue is resolved.
