### ISSUE TITLE
issue deploy openwhisk on  kubernetes

### ISSUE THREAD

**Issue by zhy989** [apache/incubator-openwhisk-deploy-kube#18]
when I run  "ansible-playbook -i environments/kube setup.yml",   the error is as below:

**fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'nginx.ssl.cert == \"openwhisk-cert.pem\"' failed. The error was: error while evaluating conditional (nginx.ssl.cert == \"openwhisk-cert.pem\"): {u'confdir': u'{{ config_root_dir }}/nginx', u'ssl': {u'path': u'{{ openwhisk_home }}/ansible/roles/nginx/files', u'cert': u'openwhisk-cert.pem', u'password_enabled': False, u'key': u'openwhisk-key.pem', u'password_file': u'ssl.pass'}, u'version': 1.11, u'port': {u'adminportal': 8443, u'api': 443, u'http': 80}}: 'config_root_dir' is undefined\n\nThe error appears to have been in '/home/h3c/zhy/git/serverless/wsk/openwhisk_k8s/incubator-openwhisk-deploy-kube/ansible/setup.yml': line 33, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: gen untrusted certificate for host\n    ^ here\n"}**

**Comment by bbrowning** [comment]
This looks like the exact error that #14 fixed. Is your git repo completely up-to-date with the latest commits?

**Comment by bbrowning** [comment]
There have been several commits since June 5th. `git pull` the latest, try again, and this error should be fixed.

**Comment by zhy989** [comment]
The issue is fixed  after update the code to the latest version, Thanks !

**Comment by daisy-ycguo** [comment]
Thank you all. Close it as it is resolved.
