### ISSUE TITLE
OpenWhisk should be deployed all through yaml

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#22]
A number of components will need to be configured so they are more "Dockerized" to remove the need for Ansible. General implementations should be able to use:
* Have Kube YAML files as the primary source of configuration
* Utilize ENVIRONMENT vars
* “bake” other configs into Docker images
* Determine if we need to do better health checking to determine if we should start. Do not fail to run a process

- [] [Nginx](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/24)
- [] [Controller](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/25)
- [] [Kafka](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/26)
- [] [Invoker](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/27)
- [] [CouchDB](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/28)
- [] [RouteMgmt](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/45)
- [x] Post Deploy script.

Components to be removed:
- [x] [Consul](https://github.com/apache/incubator-openwhisk-deploy-kube/issues/23)

The original proposal for this work can be found [here](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=70258567)

**Comment by dgrove-oss** [comment]
resolved by #130; can be closed
