### ISSUE TITLE
Remove Consul for OpenWhisk

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#23]
If all OpenWhisk components are fully configured with appropriate configuration values, we should be able to remove Consul from the OpenWhisk deployment.

- [x] Nuke Consul

**Comment by markusthoemmes** [comment]
The Controller will still attempt to write invokerHealth metrics to consul's KV. That "feature" is going away but as of today you might still need consul.

**Comment by DanLavine** [comment]
@markusthoemmes That is good to know. Is there an issue currently out there to address this? Would just like to know for reference and if we start crossing paths, we might need to shift our efforts so that work can be addressed.

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/issues/2254

**Comment by DanLavine** [comment]
Consul has been removed. However the current code relies on the Nuke Consul PR to be merged so we can move to public images.
