### ISSUE TITLE
Nginx should not need Ansible for configuration

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#24]
Ideally we need to be able to remove Ansible configuration that are used to setup Consul.

* Build Nginx with all OpenWhisk specific requirements (wsk, blackbox) pre-built into the Docker image.
* Script to helps generate certificates
* create a Kube ConfigMap and/or Secrets Resource from those certs and a static Nginx.conf file. Where this nginx.conf file is specific to an environment
* Have yaml file(s) for the Kube Deployment and Service which uses the generated ConfigMap

- [x] Nginx is configured via a yaml file with documentation
- [ ] Nginx Docker image is built via the OpenWhisk CI and is not a custom image

**Comment by dgrove-oss** [comment]
See discussion in https://github.com/apache/incubator-openwhisk/issues/2152 of what can be done upstream.

**Comment by dgrove-oss** [comment]
resolved by #130; can be closed
