### ISSUE TITLE
Enable persistent volume caused CouchDB starting failure

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-deploy-kube#244]
When I turn on `db.persistence.enabled` and use helm to install, I meet with below error when db pod is starting. I guess it might cause by the missing of PV (PersistentVolume) definition.

If we assume admin shall define their own PV in the system before running `helm install`, we shall document it.
```
  Type     Reason                 Age   From               Message
  ----     ------                 ----  ----               -------
  Normal   Scheduled              2m    default-scheduler  Successfully assigned couchdb-58bccdf649-fwjq2 to worker1
  Normal   SuccessfulMountVolume  2m    kubelet, worker1   MountVolume.SetUp succeeded for volume "default-token-w68nb"
  Warning  FailedMount            36s   kubelet, worker1   Unable to mount volumes for pod "couchdb-58bccdf649-fwjq2_openwhisk(1bf4e196-803a-11e8-a539-0227b72075f7)": timeout expired waiting for volumes to attach/mount for pod "openwhisk"/"couchdb-58bccdf649-fwjq2". list of unattached/unmounted volumes=[database-storage]
```

**Comment by dgrove-oss** [comment]
The assumption is that the cluster has enabled dynamic volume provisioning (https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/).  You are right, we should add that to the list of pre-reqs for the cluster.  I will do that.
