### ISSUE TITLE
Adding Ressource libcurl3-gnutls in couchDB Dockerfile uses deprecated link

### ISSUE THREAD

**Issue by Hazmes** [apache/incubator-openwhisk-deploy-kube#252]
https://github.com/apache/incubator-openwhisk-deploy-kube/blob/489ce8e90abf3bc411f8dd7087d42916c8a004be/docker/couchdb/Dockerfile#L7

The Link in the line above is no longer valid and return HTTP status code 404.

The closest available version available under debian/pool is libcurl3-gnutls_7.38.0-4+deb8u11_amd64.deb 
Link: http://ftp.us.debian.org/debian/pool/main/c/curl/libcurl3-gnutls_7.38.0-4+deb8u11_amd64.deb

Need to update the Link or change to a different pool.

**Comment by dgrove-oss** [comment]
Thanks for the report.  I will take a look.  I was thinking about restructuring this Dockerfile anyways, so this issue is a good excuse.

**Comment by dgrove-oss** [comment]
#261 eliminates the problem by letting us use the upstream apache/couchdb docker image directly to run couchdb and doing the database init operations in a separate Job that can use a simpler alpine-based container.
