### ISSUE TITLE
Kafka should not need Ansible for configuration

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#26]
Ideally we need to be able to remove Ansible configuration that are used to setup Kafka

* On the initial startup, Kafka should register the “health” topic.

**Comment by dgrove-oss** [comment]
Summarizing offline discussion with @DanLavine and @rabbah on this issue.

We are running kafka with autocreation of topics enabled.  But that doesn't allow us to set the various configuration parameters for the topic that are set in the ansible scripts.  It is believed setting these appropriately is important for performance.  One possible path forward is to upgrade kafka to 0.11.0.x.  The 0.11.0 release of kafka introduced the org.apache.kafka.clients.admin.AdminClient API which would allow us to create the topics with the needed configuration parameters programmatically from the controller.  This would eliminate the need for external scripting.

**Comment by dgrove-oss** [comment]
I submitted PR https://github.com/apache/incubator-openwhisk/pull/2948 to progress this.  If it is accepted, then we should be able to resolve issue with small additional effort.

**Comment by dgrove-oss** [comment]
#2948 was merged.  PR https://github.com/apache/incubator-openwhisk/pull/2991 covers the health topic.  After it is merged, I believe we can use a vanilla kafka container (won't need custom image).

**Comment by dgrove-oss** [comment]
#89 updates this project to take advantage of apache/incubator-openwhisk#2948.

**Comment by dgrove-oss** [comment]
resolved by #130; can be closed
