### ISSUE TITLE
virtual box must be installed for minikube

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-deploy-kube#263]
one needs to install virtualbox to follow the instructions for minikube setup successfully; this is not in the docs.

**Comment by bbrowning** [comment]
VirtualBox is just one of several options, depending on your host OS and preferences.

 `minikube start` takes this option:
`--vm-driver string               VM driver is one of: [virtualbox vmwarefusion kvm xhyve hyperv hyperkit kvm2 none] (default "virtualbox")`

**Comment by rabbah** [comment]
Thanks @bbrowning - should we add that to the docs?

**Comment by dgrove-oss** [comment]
I guess its a question of how much of the minikube documentation we want to replicate vs. incorporate by reference.

**Comment by dgrove-oss** [comment]
I think #335 is enough to close this (mentions in the minikube-specific docs that you need a VM in which to run minikube and the details vary depending on your host OS).
