### ISSUE TITLE
Controller waiting for couchdb giving unauthorised

### ISSUE THREAD

**Issue by cduque89** [apache/incubator-openwhisk-deploy-kube#266]
Hi.

With the latest chart version my controller readiness probe is failing because it's giving unauthorised when trying to reach couchdb.

We added the following to the readiness probe and now it works: 
````
--header=\"Authorization: Basic {{ include "db_authentication" . | b64enc }}\"
```` 
and in _helpers.tpl:
````
{{- define "db_authentication" -}}
{{ .Values.db.auth.username }}:{{ .Values.db.auth.password }}
{{- end -}}
````

Is this happening to someone else as well?

Should we open a PR?

Thanks.

**Comment by dgrove-oss** [comment]
There have been a couple of upstream PRs merged that need adjustment for in kube-deploy.  i'm working on fixing now.  Should have fixes ready today.

**Comment by cduque89** [comment]
We have opened a PR that fix this. #268 it fixed everything for us. If you have a look and agree with the changes you can merge it.
