### ISSUE TITLE
Invoker should not need Ansible for configuration

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#27]
Ideally we need to be able to remove Ansible configuration that are used to setup the Invoker

* Have only one Invoker instance be deployed to a Kube node and ensure that no other Kube Pods run alongside it as well.
   * This can be done using [node selectors](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/)

**Comment by DanLavine** [comment]
This is done with the above PR.

**Comment by DanLavine** [comment]
This issue should be closed once there is a public OpenWhisk image for the invoker that does not need Consul.

**Comment by dgrove-oss** [comment]
Closable? Handled by #50 ?
