### ISSUE TITLE
CouchDB should not need Ansible for configuration

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#28]
Ideally we need to be able to remove Ansible configuration that are used to setup CouchDB.

* Generate a Docker image with an already initialized database.
* The Docker image should have an init script that edits the authentication for unique credentials. Also edit the entries within the database with unique credentials

**Comment by DanLavine** [comment]
Currently, CouchDB is setup by using a custom script and the public CouchDB image. The script pulls all of OpenWhisk down into the container and runs though the Ansible scripts to set things up. This works for local dev and test, but we need to host the image in a more official capacity on the OpenWhisk Docker account.

**Comment by dgrove-oss** [comment]
#75 switches us to using an official openwhisk/kube-couchdb image

**Comment by dgrove-oss** [comment]
#75 was merged; this issue can be closed.
