### ISSUE TITLE
svc.cluster.local doesn't work if a customized domain is set

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-deploy-kube#298]
I'm using multiple clusters environment where the domain name is set to `mycluster.local` when starting kube-dns. Then the deployment failed because services such as `zookeeper-0.zookeeper.openwhisk.svc.cluster.local` cannot be located. The correct name is `zookeeper-0.zookeeper.openwhisk.svc.mycluster.local`.

The root reason is that `svc.cluster.local` is hard coded. A possible fix is to allow users to config the domain name in `values.yaml`.

**Comment by dgrove-oss** [comment]
makes sense to pull this out into values.yaml with a default of `svc.cluster.local`

**Comment by dgrove-oss** [comment]
PR merged.
