### ISSUE TITLE
kafka provider package fails to install missing npm

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-deploy-kube#302]
the install job for kafka provider fails because the install script [installCatalog.sh](https://github.com/apache/incubator-openwhisk-package-kafka/blob/master/installCatalog.sh#L96) requires node/npm

The [script runner](https://github.com/apache/incubator-openwhisk/blob/master/tools/scriptRunner/Dockerfile) image needs to update with node/npm

**Comment by dgrove-oss** [comment]
should be fixed by Carlos's upstream PR: https://github.com/apache/incubator-openwhisk/pull/4036.  Leaving open until fix flows through and we get a passing deploy here.

**Comment by dgrove-oss** [comment]
This is working now.
