### ISSUE TITLE
K8S resource naming conventions within functions

### ISSUE THREAD

**Issue by nerdguru** [apache/incubator-openwhisk-deploy-kube#315]
It's not entirely clear to me if this is a feature or a bug, but I thought it worth documenting anyway.  Inside a function, when referencing another resource inside the same K8S cluster, the function is unable to use K8S resource naming conventions.  

For example, suppose you have a function that is connecting to a MongoDB in the same cluster.  On other FaaS on K8S runtimes, you can make the following reference in Node.js:

```
const url = 'mongodb://fonkdb-mongodb.default:27017/guestbook_app';
MongoClient.connect(url, (err, db) => {
.
.
.
```

Where `fonkdb-mongodb.default:27017` is the connection string that is based on K8S naming conventions.  OpenWhisk returns the following:

```
failed to connect to server [fonkdb-mongodb.default:27017] on first connect [MongoError: getaddrinfo ENOTFOUND fonkdb-mongodb.default fonkdb-mongodb.default:27017]
```

You can try this out yourself with this example:

https://github.com/fonk-apps/fonk-examples/tree/master/guestbook/faas/openwhisk/nodejs

I got around it by putting a load balancer in front of the MongoDB and by passing the connection string for the MongoDB as an external resource as an environment variable.  So:

```
wsk action create list ./list/list.zip --kind nodejs:default -i --web true --param mongoHost 10.10.20.208:31094
```
where `10.10.20.208:31094` comes from:
```
$ kubectl get svc
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)           AGE
fonkdb-mongodb   LoadBalancer   10.108.54.56   10.10.20.210   27017:31094/TCP   13m
kubernetes       ClusterIP      10.96.0.1      <none>         443/TCP           1h
$ kubectl cluster-info
Kubernetes master is running at https://10.10.20.208:6443
KubeDNS is running at https://10.10.20.208:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

But it would be preferable, when running inside K8S to be able to have this work:
```
wsk action create list ./list/list.zip --kind nodejs:default -i --web true --param mongoHost fonkdb-mongodb.default:27017
```

Then again, you could argue that the function shouldn't know it's running inside a K8S cluster and the way it works is just fine.  I'm not sure what the right answer is, but I wanted to get the situation documented.

**Comment by dgrove-oss** [comment]
Thanks.  This is useful feedback; we should cover this in the configuration choices document.  

One can actually configure invokers that are using the DockerContainerFactory to use kube-dns for DNS resolution by setting an environment variable, but it is not the default and could be streamlined.  If you use the KubernetesContainerFactory than the user actions run in full-fledged Kubernetes pods and therefore use kube-dns by default (no extra configuration needed).

**Comment by nerdguru** [comment]
Thanks for this David, much appreciated.  I tend to accept the default configs, can you point me to where I'd learn how to take advantage of configuring the KubernetesContainerFactory?

**Comment by dgrove-oss** [comment]
Sorry for the slow response.  Take a look at https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/configurationChoices.md#invoker-container-factory.   I still have a todo to add a better discussion on making k8s visible to user-containers to this section of the document, but the docs will show you how to configure things to get the KubernetesContiainerFactory.
