### ISSUE TITLE
Deployment using helm seems to fail

### ISSUE THREAD

**Issue by Tabrizian** [apache/incubator-openwhisk-deploy-kube#321]
Hello,

I've tried to install OpenWhisk using Helm. But all of the services don't become available. Here is the output of my ```myvalues.yaml``` and ```kubectl get pods -n openwhisk```.

```yaml
whisk:
  ingress:
    type: NodePort
    api_host_name: 172.25.21.82
    api_host_port: 31001
```

```
NAME                          READY   STATUS     RESTARTS   AGE
apigateway-7d6b597cd7-9fdgz   1/1     Running    0          7h56m
controller-0                  0/1     Init:1/2   0          7h56m
couchdb-54554d67b6-5jjpc      1/1     Running    0          7h56m
init-couchdb-5gvll            0/1     Error      0          7h54m
init-couchdb-w6rzx            0/1     Error      0          7h56m
invoker-k5b8s                 0/1     Init:0/2   0          7h56m
invoker-qxk9l                 0/1     Init:0/2   0          7h56m
kafka-0                       1/1     Running    2          7h56m
nginx-cddd5f886-7fhb7         1/1     Running    0          7h56m
redis-796c59d997-96r2h        1/1     Running    0          7h56m
zookeeper-0                   1/1     Running    0          7h56m
```

Also, this is the log files for the ```init-couchdb-5gvll``` pod.

```
Cloning into '/openwhisk'...
fatal: unable to access 'https://github.com/apache/incubator-openwhisk/': Failed to connect to github.com port 443: Connection refused
```

**Comment by dgrove-oss** [comment]
The error on the init couchdb Job is the reason why the other services do not become available.  The init containers on the controller and invoker are waiting for the init-couchdb Job to succeed.   Are you behind a firewall that is blocking access to github.com?

**Comment by Tabrizian** [comment]
I'm using HTTP Proxy to access the outside network. It has worked perfectly fine in other situations. Is there any way to debug this issue and find the root cause of the problem?

**Comment by dgrove-oss** [comment]
I would suggest running the openwhisk/ansible-runner:latest pod interactively via `kubectl run testit -it --image=openwhisk/ansible-runner:latest --command /bin/bash` and trying the git clone manually from the shell within the running pod to verify network connectivity.

**Comment by wcorbett36** [comment]
I encountered a similar issue on windows and the logs reported windows to unix conversion line break issue originating from some of the shell scripts placed by helm...

**Comment by Tabrizian** [comment]
Thanks. I got it back to work. Seemed to be some networking problems.

**Comment by shakshisinghai** [comment]
@Tabrizian 
I am facing a similar issue. Could you please let me know how to resolve the networking issue?

**Comment by SeyedHosseinTafakh** [comment]
i had the same problem. it turns out calico was not set up properly and Kubernetes cluster couldn't connect internet.
