### ISSUE TITLE
Why nginx pod is suppsedly supposed to be installed on kube-node-2 on kubeadm-dind-cluster?

### ISSUE THREAD

**Issue by JiniousChoi** [apache/incubator-openwhisk-deploy-kube#337]
I am not so sure with the following quote from the main README.md on this project:

>  If you are using kubeadm-dind-cluster, use the command kubectl describe node kube-node-2 | grep InternalIP to determine the value for api_host_name

How come one can be so sure that the nginx pod should be installed on kube-node-2? 
Maybe I am getting it wrong but it sounds to me like the nginx will be installed on kube-node-2, guaranteed, so we only need to grep InternalIP of the kube-node-2.

Even if it's always the case it seems working with a implicit/hidden mechanism. Would you comment regarding this on the README.md?

Actually, last time I saw the nginx on kube-node-1 when I couldn't deploy Openwhisk on kubeadm-dind-cluster properly. Anyway, in some erroneous case, nginx pod wouldn't end up on kube-node-2 and that 's an issue.

FYI,
(I am on my ubuntu on macbook)
```
jinc@jinc-MacBookPro:~/github$ kubectl get nodes --show-labels
NAME          STATUS    ROLES     AGE       VERSION   LABELS
kube-master   Ready     master    4m        v1.10.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-master,node-role.kubernetes.io/master=
kube-node-1   Ready     <none>    3m        v1.10.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-node-1,openwhisk-role=invoker
kube-node-2   Ready     <none>    3m        v1.10.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=kube-node-2,openwhisk-role=invoker
```

**Comment by dgrove-oss** [comment]
I will try to make the docs clearer.  I was assuming people knew too much about kubernetes.  A NodePort ingress is made available on every worker-node, so choosing kube-node-1 vs. kube-node-2 doesn't actually matter.  Either way the request will be forwarded to the nginx service, which will forward to the nginx pod.

**Comment by dgrove-oss** [comment]
Clarified docs in #335
