### ISSUE TITLE
Simple typo in readme

### ISSUE THREAD

**Issue by atsag** [apache/incubator-openwhisk-deploy-kube#342]
In the section [https://github.com/apache/incubator-openwhisk-deploy-kube#using-a-kubernetes-cluster-from-a-cloud-provider](url) of the README.md file, the link to the technical requirements in the first line should be edited to remove an extraneous bracket `[` and become [https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-technical-requirements.md](url)

**Comment by dgrove-oss** [comment]
Thanks for the report.
