### ISSUE TITLE
pushes to dockerhub of invoker-agent image should tag with githash

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-deploy-kube#359]
We should tag docker images pushed to dockerhub with the short form of the githash (same as done by core repo's Jenkins job).

**Comment by dgrove-oss** [comment]
Needed as part of #353

**Comment by csantanapr** [comment]
Which images your referring?

**Comment by csantanapr** [comment]
Most already have this. maybe not all and some are missing?

**Comment by dgrove-oss** [comment]
The invoker-agent image that is pushed from the kube-deploy repo is the only one I have found so far that is missing this.

**Comment by csantanapr** [comment]
Ah OK, then yes use same thing we do with the runtimes
https://github.com/apache/incubator-openwhisk-runtime-docker/blob/master/tools/travis/publish.sh#L52
```
SHORT_COMMIT=`git rev-parse --short HEAD`
```
