### ISSUE TITLE
issue about span job to other node

### ISSUE THREAD

**Issue by zhy989** [apache/incubator-openwhisk-deploy-kube#36]
If there are too many jobs to run ,  how the system(openwhisk on kubernetes ) span jobs to other node ?
kubenetes span openwhisk components or job to other node?

If a new job come, openwhisk restart a docker container to run the job, right?  how does openwhisk allocate and free resource? resource is managed by openwhisk or by kubernetes ? and when do kubernetes span openwhisk components or  job to other node?  how to load balance?

Anyone who can help me?

**Comment by rabbah** [comment]
The invoker manages a pool of containers (say in a pod) and the load balancer (part of the controller) distributes load to invokers. If you add new invokers they register with the load balancer so it can use them. 

The reason for the custom container manager is for promoting container reuse and cut latency of allocating containers.

**Comment by zhy989** [comment]
@rabbah Thanks a lot
  It's mean that we can increase the number of invoker to parallel the job threads. The pool of containers is managed by invoker . Actually the container resource is managed by docker engine,right? and the docker engine can manage the resource of this node(kubernetes slave node) it run on. 
  Can the invoker allocate resource on other node(kubernetes slave node) ? I think no 
  I want to know how to span job to other node when resource is not enough on one node .
  Span openwhisk components and job  or just job to other node ? Span is managed by openwhisk or by kubernetes?

**Comment by zhy989** [comment]
@rabbah thanks
The container which invoker managed is allocated in invoker container or  on the localhost? The pool of containers is running  in the invoker container or on the host?

**Comment by dgrove-oss** [comment]
I think this issue can be closed.  Can someone with the right privileges please close it?
