### ISSUE TITLE
Where is docs/ingress.md?

### ISSUE THREAD

**Issue by xieweicarl2018** [apache/incubator-openwhisk-deploy-kube#379]
In the file helm/openwhisk/values.yaml, I see the following note:

whisk:
  # Ingress defines how to access OpenWhisk from outside the Kubernetes cluster.
  # See docs/ingress.md for a discussion of how to provide these values.

But I can not find out the file docs/ingress.md, where is it? Please help!  Thanks!

**Comment by daisy-ycguo** [comment]
ingress.md has been split into several parts and moved to the document for specific k8s clusters. You can find the ingress configuration there.

* [Docker for Mac](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-docker-for-mac.md#configuring-openwhisk)
* [kubeadm-dind-cluster](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-dind-cluster.md#configuring-openwhisk)
* [Minikube](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-minikube.md#configuring-openwhisk)
* [IBM (IKS)](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-ibm-public.md#configuring-openwhisk)
* [Google (GKE)](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-google.md#configuring-openwhisk)
* [Amazon (EKS)](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/k8s-aws.md#configuring-openwhisk)

**Comment by dgrove-oss** [comment]
@xieweicarl2018  - thanks for reporting the dangling reference in the docs.  I have submitted a PR to fix values.yaml (as described by @daisy-ycguo above).
