### ISSUE TITLE
Openwhisk fails after cluster reboot due to no persistence

### ISSUE THREAD

**Issue by MichielVanderlee** [apache/incubator-openwhisk-deploy-kube#39]
I'm running a Kubernetes cluster in Vagrant for testing and noticed that on reboot, openwhisk fails because  the couchdb and consul data is not persisted.

I've already made the required changes in my fork and it's all working.
PR incoming.

**Comment by dgrove-oss** [comment]
Working on a PR to account for couchdb, zookeeper, kafka, and apigateway(redis).

**Comment by dgrove-oss** [comment]
PR #153 pending; hoping to merge within the next few days.
