### ISSUE TITLE
Document all entries in values.yaml

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-deploy-kube#398]
We should uniformly document the meaning of every entry in values.yaml.

One possible way to do this is to adopt the values-metadata.yaml file that is used for OpenWhisk on IBM Cloud Private's community chart and maintain it here.

@neeraj-laad if you think maintaining values-metadata.yaml in the upstream project is a viable approach, please submit a PR here with the initial version (we can update in a second PR if necessary).

**Comment by neeraj-laad** [comment]
@dgrove-oss I have bene thinking about this for last few days and that is probably the best way to maintain the names, description etc of all parameters. Will submit a PR today.
