### ISSUE TITLE
Zookeeper fails to start

### ISSUE THREAD

**Issue by jonathanschwarze** [apache/incubator-openwhisk-deploy-kube#421]
After a fresh install via helm the zookeeper is broken. Pod is running but logs give me:
```
0
tickTime=2000
clientPort=2181
initLimit=5
syncLimit=2
dataDir=/data
dataLogDir=/datalog
server.0=owdev-zookeeper-0.owdev-zookeeper.openwhisk.svc.cluster.local:2888:3888
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.server.quorum.QuorumPeerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
Every other component works fine.

**Comment by dgrove-oss** [comment]
The `log4j` warnings are normal output.   If kafka is working, then zookeeper must be operating correctly.

**Comment by jonathanschwarze** [comment]
Thx @dgrove-oss. I'm still investigating issues with an error `"error":"The server is currently unavailable (because it is overloaded or down for maintenance)."` HTTP failure 503. But Zookeeper is fine so I close this issue. Controller says `failed to schedule managed action, invokers to use: Map(Unhealthy -> 2)` & `No invokers available` `[ActionsApi] [POST] failed in loadbalancer: No invokers available` I had this issue last year when controller and invoker were out of sync image versions and persistence was disabled. With the newest version I can't find the root cause. Any idea @dgrove-oss?

**Comment by dgrove-oss** [comment]
If the controller is reporting no healthy invokers
> Controller says failed to schedule managed action, invokers to use: Map(Unhealthy -> 2) & No invokers available
then it probably means that the `healthAction` failed to run successfully on the invoker.  Dig into an invoker log and see if you can find log output related to executing a healthAction.  Could fail for a bunch of reasons (problem creating container, problem getting the action code from the couchdb, ...)
