### ISSUE TITLE
Use wildcard for kubeVersion in Chart.yaml 

### ISSUE THREAD

**Issue by rahulqelfo** [apache/incubator-openwhisk-deploy-kube#424]
Currently  the kubeVersion is hardcoded to ` kubeVersion: ">=v1.10.0-" ` in Chart.yaml . When I try to deploy it on the aws EKS cluster it throws the following error:

```
sudo helm install ./helm/openwhisk --namespace=openwhisk --name=owdev -f $HOME/ow-deploy/mycluster.yaml
Error: Chart requires kubernetesVersion: >=v1.10.0 which is incompatible with Kubernetes v1.10.11-eks
```
A work around for this is to use wildcard in the Chart.yaml file to over come this problems:
`kubeVersion: ">=v1.10.0-r0"`

The above works fine for me . If this fix is good then I can raise a PR for this .

**Comment by dgrove-oss** [comment]
The fix seems plausible to me; please go ahead and submit a PR. For posterity, here's a good discussion of the problem https://github.com/helm/helm/issues/3810
