### ISSUE TITLE
Helm install fails if repository is cloned from Windows / line-endings

### ISSUE THREAD

**Issue by andreialecu** [apache/incubator-openwhisk-deploy-kube#432]
I was debugging a problem with `init-couchdb` pods showing an `Error` state and the cluster never coming up properly. 

Upon further investigation I noticed the following problem in the logs:

```bash
$ kubectl logs owdev-init-couchdb-4l5l2 -n openwhisk
/task/initdb.sh: line 3: $'\r': command not found
```
I initially cloned this repository from the windows command line, so the line endings probably came up wrong due to auto CRLF conversion and due to them being fed by `helm` to `docker`, it broke everything.

I was able to get it to properly execute by firing up bash on Ubuntu via Windows Subsystem for Linux, cloning from there, and running `helm` via that cloned repository, indeed confirming the CRLF issue.

I believe this repository or other related repos need a `.gitattributes` file in order to prevent this.

See: https://techblog.dorogin.com/case-of-windows-line-ending-in-bash-script-7236f056abe

**Comment by rabbah** [comment]
👍

This is the one used on the “openwhisk” repo https://github.com/apache/incubator-openwhisk/blob/master/.gitattributes

If you send a PR I’m happy to merge it.

**Comment by andreialecu** [comment]
Submitted PR #433
