### ISSUE TITLE
Event providers are disabled by default

### ISSUE THREAD

**Issue by mohammed-ali-1** [apache/incubator-openwhisk-deploy-kube#439]
Hello,

The documentation [here](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/configurationChoices.md#selectively-deploying-event-providers) says that:

> The default settings of the Helm chart will deploy OpenWhisk's alarm, cloudant, and kafka event providers.

But that is not true. The default behaviour of the OpenWhisk Helm chart is that all event providers are disabled (see screenshot from the `values.yaml` file of the Helm chart). 

![image](https://user-images.githubusercontent.com/27845458/53578368-d740b580-3b77-11e9-988d-0a05b7db691a.png)

**Comment by dgrove-oss** [comment]
Not sure where you are getting that yaml, but it is out of date.   See https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/values.yaml#L303-#L338

**Comment by mohammed-ali-1** [comment]
Oh sorry, my bad. It seems that I was using version 0.1.3 of the Helm chart.
