### ISSUE TITLE
Explicit pre-reqs for OpenWhisk installation

### ISSUE THREAD

**Issue by RobertJBarron** [apache/incubator-openwhisk-deploy-kube#440]
Please details the find the hardware/virtual hardware pre-requisites for running OpenWhisk? https://openwhisk.apache.org/documentation.html#pre-requisites hints that it can be run on any laptop, but even these have a hardware range.

How much Memory/CPU/Disk should I dedicate to installing OpenWhisk? Standalone and as part of a Kubernetes cluster like IBM Cloud Private.

Thanks!

**Comment by RobertJBarron** [comment]
@dgrove-oss, @csantanapr tells me you're the best person for this job!

:)

**Comment by csantanapr** [comment]
@dgrove-oss Can we say that the minimum could be 2vCPU 4GB RAM 1 node cluster, this would be similar on what we run in CI in Travis today.

This should be good to get a small environment, then user if they have requirements for performance and HA they can increase the number of node and the CPU&Mem for each node.
