### ISSUE TITLE
Install Route Management from the script

### ISSUE THREAD

**Issue by DanLavine** [apache/incubator-openwhisk-deploy-kube#45]
Ideally we need to be able to remove Ansible configuration that are used to setup RouteManagement. To do this, we should be able to run the script by hand when it is pointed at an OpenWhisk deployment.

**Comment by DanLavine** [comment]
closed wrong issue. should ave been the post deploy

**Comment by xingzhou** [comment]
So user shall manually install this package after deployment is finished? or if there is any check to validate whether the OW environment is ready?

**Comment by dgrove-oss** [comment]
working on a fix now.

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk-deploy-kube/commit/9f8e75d7ac221c6314ad9bc2d2547baa9306ddf8.
