### ISSUE TITLE
When deploying with an external couchdb you get those errors in the log

### ISSUE THREAD

**Issue by sciabarra** [apache/incubator-openwhisk-deploy-kube#453]
Enabling single node cluster
{"error":"unknown_error","reason":"badarg","ref":2908461478}
Disabling reduce limits on views
{"error":"not_found","reason":"no such node: couchdb@couchdb0"}
/openwhisk/ansible /

**Comment by dgrove-oss** [comment]
Thanks!  Did not realize from the slack message it was an external db.  We probably need to propagate a different value for nodename here https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/configMapFiles/initCouchDB/initdb.sh#L47

**Comment by sciabarra** [comment]
I actually fixed with "db_protocol=$DB_PROTOCOL" there it was trying to access in http a database in https:

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----
