### ISSUE TITLE
Deployment into OpenShift

### ISSUE THREAD

**Issue by diosadentro** [apache/incubator-openwhisk-deploy-kube#473]
Is there any documentation available around generating a mycluster.yaml file to support an openshift deployment. Helm charts can be used to deploy applications into openshift, just not sure what the mycluster.yaml needs to support this type of deployment.

**Comment by dgrove-oss** [comment]
There's a PR pending with a first cut based on some mailing list discussion a couple weeks back.  Take a look at #465.  I'd love to get help improving the docs.

**Comment by dgrove-oss** [comment]
Merged #465.  Please give it a try.
