### ISSUE TITLE
Error: could not find tiller

### ISSUE THREAD

**Issue by SamChb72** [apache/incubator-openwhisk-deploy-kube#495]
System: Ubuntu 18.04.2 LTS
Docker version 18.09.7, build 2d0083d

I have error:
incubator-openwhisk-deploy-kube$ helm install ./helm/openwhisk --namespace=openwhisk --name=owdev -f mycluster.yaml
Error: could not find tiller

**Comment by dgrove-oss** [comment]
Did you do the `helm init` command for this cluster? https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docs/helm.md

**Comment by SamChb72** [comment]
yes, you’re right, it wasn’t initiated.
by the way, what values should I put for auth in line?
wsk property set --auth 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

Best Regards, Cordialement

**Comment by SamChb72** [comment]
yes, h'as ok now ;-) thanks
