### ISSUE TITLE
whiskconfig.conf is using short header - breaks with current scancode

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-deploy-kube#501]
https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/whiskconfig.conf

Should this be changed to use the full license header version? Build is broken due to the recent more stringest scancode updates.

**Comment by dgrove-oss** [comment]
yes.  will be fixed in #500 which I should be merging in about an hour (as soon as travis clears it)

**Comment by dgrove-oss** [comment]
fix merged.
