### ISSUE TITLE
Failed to connect to couchdb.openwhisk port 5984: Connection timed out

### ISSUE THREAD

**Issue by akhuddus** [apache/incubator-openwhisk-deploy-kube#53]
Here is the log tail when tried to bring CouchDB on K8S.

`+ ansible-playbook -i environments/local setup.yml -e db_host=couchdb.openwhisk -e db_prefix=test_ -e db_username=whisk_admin -e db_password=some_passw0rd -e db_port=5984 -e openwhisk_home=/openwhisk
CouchDB is up and running
/openwhisk/ansible /openwhisk /var/lib/couchdb

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.024)       0:00:00.024 ******
ok: [localhost]

TASK [find the ip of docker-machine] *******************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.548)       0:00:00.572 ******
skipping: [localhost]

TASK [get the docker-machine ip] ***********************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.027)       0:00:00.600 ******
skipping: [localhost]

TASK [gen hosts for docker-machine] ********************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.032)       0:00:00.633 ******
skipping: [localhost]

TASK [add new db host on-the-fly] **********************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.029)       0:00:00.662 ******
skipping: [localhost]

TASK [check if db_local.ini exists?] *******************************************
Monday 11 September 2017  18:31:50 +0000 (0:00:00.025)       0:00:00.688 ******
ok: [localhost]

TASK [prepare db_local.ini] ****************************************************
Monday 11 September 2017  18:31:51 +0000 (0:00:00.267)       0:00:00.955 ******
changed: [localhost -> localhost]

TASK [gen untrusted server certificate for host] *******************************
Monday 11 September 2017  18:31:51 +0000 (0:00:00.437)       0:00:01.392 ******
changed: [localhost -> localhost]

TASK [gen untrusted client certificate for host] *******************************
Monday 11 September 2017  18:31:51 +0000 (0:00:00.320)       0:00:01.713 ******
changed: [localhost -> localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0

Monday 11 September 2017  18:31:52 +0000 (0:00:00.394)       0:00:02.108 ******
===============================================================================
Gathering Facts --------------------------------------------------------- 0.55s
prepare db_local.ini ---------------------------------------------------- 0.44s
gen untrusted client certificate for host ------------------------------- 0.39s
gen untrusted server certificate for host ------------------------------- 0.32s
check if db_local.ini exists? ------------------------------------------- 0.27s
get the docker-machine ip ----------------------------------------------- 0.03s
gen hosts for docker-machine -------------------------------------------- 0.03s
find the ip of docker-machine ------------------------------------------- 0.03s
add new db host on-the-fly ---------------------------------------------- 0.03s
/openwhisk /var/lib/couchdb
+ popd
+ curl -X PUT http://couchdb.openwhisk:5984/_config/admins/whisk_admin -d '"some_passw0rd"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
curl: (7) Failed to connect to couchdb.openwhisk port 5984: Connection timed out

`

**Comment by DanLavine** [comment]
Sounds like your issue is that you cannot use a Pod's service to communicate back with the pod. I had put a troubleshooting guid in another section of the READMEs for this, but maybe I need a more general section. This used to only happen for Kafka. [Link](https://github.com/apache/incubator-openwhisk-deploy-kube/tree/master/kubernetes/kafka#troubleshooting)

**Comment by akhuddus** [comment]
Not tried promiscuous mode but updating container env var DB_HOST to localhost worked in one of clusters. In another cluster it just worked without change. We yet to figure out the inconsistency in our cluster. 

Thanks Dan for the quick response!
