### ISSUE TITLE
Specifying a path to OpenWhisk directory causes docker/build.sh to exit 1

### ISSUE THREAD

**Issue by mlangbehn** [apache/incubator-openwhisk-deploy-kube#6]
## Summary

Currently, specifying an OpenWhisk directory when running `docker/build.sh` causes a silent exit 1.

## Reason and proposed solution

The reason can be found on [line 28 of `docker/build.sh`](https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/docker/build.sh#L28):

```shell
26 else
27   OPENWHISK_DIR="$2"
28 exit 1
29 fi
```

Removing this line resolves the issue.

**Comment by mrutkows** [comment]
@mlangbehn Hi Matt, good catch... will look at your PR...

**Comment by mrutkows** [comment]
Fixed by https://github.com/apache/incubator-openwhisk-deploy-kube/pull/7

**Comment by mrutkows** [comment]
Fixed by https://github.com/apache/incubator-openwhisk-deploy-kube/pull/7
