### ISSUE TITLE
Do we want to support package deployment using kubectl ?

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-deploy-kube#69]
I have written yaml files to deploy alarm package and catalog package and saved in my own [repo](https://github.com/daisy-ycguo/openwhisk-deploy-kube-packages). Do we want to include them in this repo ?

**Comment by dgrove-oss** [comment]
I think it makes sense to have a batch job to automate the package deployment.

It would be nice if we could move some of our custom docker images (dgrove, danlavine, daisyycguo, etc.) into a more stable namespace at dockerhub.  I'll raise that on the dev list to see if we can easily do something.

**Comment by dgrove-oss** [comment]
I've put together #126 that installs the basic catalog using an official image published to dockerhub under the openwhisk id.

**Comment by dgrove-oss** [comment]
resolved by #126; can be closed
