### ISSUE TITLE
Nginx can not forward the following requests to controller once the major controller is restarted.

### ISSUE THREAD

**Issue by xingzhou** [apache/incubator-openwhisk-deploy-kube#77]
When deploy with multiple controllers in the cluster, the nginx node is configured as load-balance mode. e.g. if we deploy two controllers, there would be controller-0 and controller-1 in the cluster, controller-0 would be the major controller node and controller-1 is the stand by controller.

In this case, if we kill controller-0, K8s will auto restart this pod, but after this controller instance is restarted, the nginx stopped to forward client request to controller pod, therefore, the client can not reach out to whisk cluster.

/cc @dgrove-oss

**Comment by xingzhou** [comment]
Took some investigation on how Nginx resolve domain name, and found out that Nginx will cache the resolved IP until next time restart or reload configurations.

Here is a [blog](https://www.nadeau.tv/nginx-proxy_pass-dns-cache/) discussing this issue. 

So for now, we have some solutions to try:
1. For `proxy_pass` config, we can try to use a var instead of a url, but this only works for single url, not the groups in upstream directive. In our case, we are using multiple controllers for HA, so this is not a good choice for us.

2. Use Nginx PLUS, which is a non-free commercial edition of Nginx.

3. There is a free Nginx module [here](https://github.com/GUI/nginx-upstream-dynamic-servers), can resolve the dynamic DNS name resolve issue. But since it's not official modules, the license and compatibility can be problems.

4. Periodically reload(not restart) the Nginx, this may force Nginx to re-resolve DNS names.

For now, I'm thinking only #4 might be an option for us, @daisy-ycguo, @DanLavine and @dgrove-oss , your comments?

**Comment by dgrove-oss** [comment]
@xingzhou and I discussed offline this morning.  

I think another option is now possible.  The upstream openwhisk now supports active-active controller replication.  We can enable this for kubernetes, and then connect nginx to the controller service (instead of to a specific instance of the stateful set).  I will take a look at doing this within the next day or two unless someone else beats me to it.

**Comment by dgrove-oss** [comment]
#85 is work in progress on this issue.

However, doesn't resolve the issue.  When I invoke actions I can see from the logs of controller-0 and controller-1 that the load is split between the two of them.  If I then kill the pod of controller-0, and wait a minute or two for kubernetes to restart it, I still see 50% of the actions timing out on trying to talk to the defunct controller-0 before running on controller-1.  The logs for the new controller-0 show it is healthy again, but even after 5 minutes it is still not receiving an incoming actions.

Probably need some additional nginx configuration to flush its cache of failed attempts/connections and actually try again.

**Comment by dgrove-oss** [comment]
After some experimentation and reading many blog post, I figured out an incantation in nginx.conf that seems to work.  #85 updated to include it.

**Comment by dgrove-oss** [comment]
@xingzhou Please verify that the change merged in #85 fixes this problem; if it does this issue can be closed.

**Comment by xingzhou** [comment]
@dgrove-oss  @daisy-ycguo and I we tried the code these days and from the multi-controllers log we can see that all the controller instances can receive the requests from the client. So I'm thinking the code can fix the problem. Also, I've added the code into the Helm project as well, so I think we can close the issue right now.
