### ISSUE TITLE
The function of API gateway needs package 'RouteMgmt' installed

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-deploy-kube#79]
We shall execute the script somewhere, or else API gateway cannot work well.
Refer to this script [installRouteMgmt.sh](https://github.com/apache/incubator-openwhisk/blob/master/ansible/roles/routemgmt/files/installRouteMgmt.sh)

**Comment by dgrove-oss** [comment]
working on a fix now.

**Comment by rabbah** [comment]
Closed by https://github.com/apache/incubator-openwhisk-deploy-kube/commit/9f8e75d7ac221c6314ad9bc2d2547baa9306ddf8.
