### ISSUE TITLE
Adjust build script to assume git clone of "incubator-openwhisk"

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-deploy-kube#8]
Looking at the build scripts setting up the OPENWHISK_DIR env. var. from issue:
https://github.com/apache/incubator-openwhisk-deploy-kube/issues/6

It seemed wrong to default to a directory for openwhisk that did not reflect a "git clone" which would place the code in an /incubator-openwhisk/... path.

In addition, we need to be aware that the OW CLI will be moving out of incubator-openwhisk this month into its own repo (with plug-in Go client) here:
https://github.com/apache/incubator-openwhisk-cli

Perhaps we need a means to establish a consistent "environment" based upon openstack repo. paths that all scripts could use?

**Comment by dgrove-oss** [comment]
@mrutkows is this issue still relevant?

**Comment by dgrove-oss** [comment]
I believe this issue can be closed as obsolete.
