### ISSUE TITLE
config container DNS using environment INVOKER_CONTAINER_DNS

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-deploy-kube#86]
We need to add an environment INVOKER_CONTAINER_DNS to invoker yaml file, which will allow action containers to resolve Kubernetes name services.

**Comment by perryao** [comment]
@dgrove-oss Is there a solution for this?

**Comment by dgrove-oss** [comment]
I submitted a PR to add the plumbing.  You'll need to know the right dns servers to use, which are probably specific to your deployment.
