### ISSUE TITLE
Couchdb Cannot be started

### ISSUE THREAD

**Issue by softputer** [apache/incubator-openwhisk-deploy-kube#88]
Couchdb is started by the command `kubectl create  -f couchdb`, but couchdb is not rightly started.
and curl http://localhost:5984/test_activations get error response.

![screenshot from 2017-11-20 13 05 08](https://user-images.githubusercontent.com/10970097/33003159-df8d173a-cdf3-11e7-99d4-f55a927c2907.png)

**Comment by dgrove-oss** [comment]
@softputer are you still stuck on this?  We've merged a number of fixes in the last week; might be worth trying again with latest code.
