### ISSUE TITLE
Enable pod/node affinity/anti-affinity in the deployment

### ISSUE THREAD

**Issue by xingzhou** [apache/incubator-openwhisk-deploy-kube#99]
The following deployment policy can help improve the performance and robustness of the deployed OpenWhisk cluster:
1. controller instance, invoker instance and other services, like kafka, couchdb, can not be deployed on the same K8s node.
2. For HA purpose, one K8s node can not run more than 1 controller instance or invoker instance

Helm project has implemented a draft version of the above policies by using K8s node affinity and pod affinity/anti-affinity, FYI.

/cc @daisy-ycguo & @dgrove-oss

**Comment by dgrove-oss** [comment]
This makes sense.  We will pick up some of these deployment policies when we merge the daemon set changes from https://github.com/apache/incubator-openwhisk-deploy-kube/pull/55.  I'm working on rebasing those now; I hope to merge by the end of the week.
